spring:
  datasource:
    url: "jdbc:h2:file:./data/nekoshlink.db;AUTO_SERVER=TRUE"
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    hibernate:
      ddl-auto: "update"
  main:
    banner-mode: "console"

logging:
  level:
    root: info
    org.springframework.security: debug

nekoshlink:
  initial-default-domain: "http://localhost:8080"
  shortener:
    hashids:
      salt: "R-Q9qQxh(7pS7MZuI!2lA/jMEfwiVe36"
