spring:
  datasource:
    url: "jdbc:h2:file:./data/nekoshlink.db;AUTO_SERVER=TRUE"
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    hibernate:
      ddl-auto: "update"
  main:
    banner-mode: "console"

server:
  port: 8443
  ssl:
    enabled: true
    key-alias: "localhost"
    key-password: "${PASSWORD}"
    key-store: "certs/keystore.jks"
    key-store-password: "${PASSWORD}"
    client-auth: "want"
    trust-store: "certs/truststore.jks"
    trust-store-password: "${PASSWORD}"

logging:
  level:
    root: info
    org.springframework.security: debug

nekoshlink:
  initial-default-domain: "https://localhost:8443"
  security:
    api-key: "federicomestrone"
  shortener:
    hashids:
      salt: "R-Q9qQxh(7pS7MZuI!2lA/jMEfwiVe36"
