spring:
  datasource:
    url: "jdbc:h2:file:./data/nekoshlink.db;AUTO_SERVER=TRUE"
  jpa:
    hibernate:
      ddl-auto: "update"
  main:
    banner-mode: off

logging:
  pattern:
    console: ""
  level:
    root: info
  file:
    path: ./logs

nekoshlink:
  security:
    api-key: "federicomestrone"
  initial-default-domain: "https://localhost:8443"
  shortener:
    hashids:
      salt: "R-Q9qQxh(7pS7MZuI!2lA/jMEfwiVe36"
